definitions:
  config:
    /hippo:namespaces/folderctxmenusdemo/basedocument:
      jcr:primaryType: hipposysedit:templatetype
      jcr:mixinTypes: ['mix:referenceable']
      jcr:uuid: d699b2a4-78fe-442e-b5f0-a2b073648a45
      /hipposysedit:nodetype:
        jcr:primaryType: hippo:handle
        jcr:mixinTypes: ['mix:referenceable']
        jcr:uuid: 68e4e4ad-c791-4d04-ac23-59d550fc3bf0
        /hipposysedit:nodetype:
          jcr:primaryType: hipposysedit:nodetype
          jcr:mixinTypes: ['hipposysedit:remodel']
          hipposysedit:supertype: ['hippo:document', 'hippostdpubwf:document', 'hippostd:publishableSummary']
          hipposysedit:uri: http://www.onehippo.org/folderctxmenusdemo/nt/1.0
